import Navbar from "@/components/navbar";
import DashboardSidebar from "@/components/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex flex-col font-manrope bg-custom-foreground w-screen h-screen max-h-screen px-[30px] pb-[40px]">
      {/* Logo + Navbar */}
      <div className="">
        <Navbar />
      </div>
      <div className="flex gap-x-[30px] w-full">
        <div className="w-[250px]">
          <DashboardSidebar />
        </div>
        <div className="w-[calc(100vw-250px)]">{children}</div>
      </div>
    </div>
  );
}
